#
<<<<<<< HEAD
#Thu Jun 11 16:45:45 COT 2026
=======
#Thu Jun 11 14:00:16 COT 2026
>>>>>>> b1369c88e0ec53e0d5bbe41a3e1b2738e705e304
platform=ANY
version=
name=proyecto
unhandledPromptBehavior=ignore
chrome.switches=--disable-infobars,--disable-notifications
browserName=chrome
